from yaduha.language import VocabEntry

# Vocabulary sourced from:
# - 50 training-slice examples in americasnlp2026/data/pilot/wixarika.jsonl
# - Iturrioz & Gomez, Gramatica Wixarika
# - http://wixar.blogspot.com/ "Aprendiendo Wixarika (Huichol)"
#   (ki = casa; ha = agua; hai = nube; wita = hilo; wiki = pajaro;
#    xapa = libro; hikuri = peyote; kiriwa = canasta; xutsi = calabaza;
#    xukuri = jicara; ku = vibora; kutuni = blusa; 'iwi = falda;
#    kuraru = establo/corral)
# - native-languages.org/huichol_words.htm
# - http://turing.iimas.unam.mx/wix (Wixarika-Spanish dictionary)
# - ASJP Database wordlist for Huichol
# - Encyclopedia.com Huichol Religion article (tatewari = fire/grandfather;
#   tayaupa = sun/father; nierika = sacred vision/tablet; mara'akame = shaman)
# - Wikipedia article on Huichol people (tukipa = ceremonial center,
#   kiekari = community)
# - geo-mexico.com article (toto/tutu = flower; maxa = deer; kwaxi = tail)
# - universoshuicholes.inah.gob.mx (xutsi = squash; hikuri = peyote;
#   muwieri = prayer arrow; nierika = sacred disk)
#
# Orthographic note: + represents the high central vowel /ɨ/.
# Acute accents mark non-default (non-penultimate) stress.
# Apostrophe ' represents the glottal stop /ʔ/.

NOUNS = [
    # People
    VocabEntry(english="woman", target="uká"),
    VocabEntry(english="man", target="teví"),
    VocabEntry(english="child", target="'uxi"),
    VocabEntry(english="baby", target="nunutsi"),
    VocabEntry(english="person", target="wixárika"),
    VocabEntry(english="people", target="te+teri"),
    VocabEntry(english="young_person", target="temaik+"),
    VocabEntry(english="boy", target="tevi"),
    VocabEntry(english="girl", target="'uxi"),
    VocabEntry(english="family", target="yunaime"),
    VocabEntry(english="shaman", target="mara'akame"),
    VocabEntry(english="governor", target="tatuwani"),
    VocabEntry(english="elder", target="kawiteru"),
    VocabEntry(english="friend", target="iwama"),
    # Animals
    VocabEntry(english="dog", target="chíki"),
    VocabEntry(english="horse", target="puritu"),
    VocabEntry(english="bull", target="wakaitsi"),
    VocabEntry(english="cow", target="tewáxi"),
    VocabEntry(english="sheep", target="muxatsi"),
    VocabEntry(english="goat", target="muxa"),
    VocabEntry(english="bird", target="wiki"),
    VocabEntry(english="fish", target="tsapa"),
    VocabEntry(english="deer", target="máxa"),
    VocabEntry(english="rabbit", target="tatsiu"),
    VocabEntry(english="snake", target="ku"),
    VocabEntry(english="eagle", target="werika"),
    VocabEntry(english="chicken", target="tsikeru"),
    VocabEntry(english="turkey", target="turuki"),
    VocabEntry(english="donkey", target="pu'uku"),
    VocabEntry(english="animal", target="t+ri"),
    VocabEntry(english="butterfly", target="kukuru"),
    # Food & plants
    VocabEntry(english="food", target="ikwai"),
    VocabEntry(english="corn", target="+kú"),
    VocabEntry(english="tortilla", target="paapá"),
    VocabEntry(english="flower", target="tutú"),
    VocabEntry(english="tree", target="kiye"),
    VocabEntry(english="squash", target="xutsi"),
    VocabEntry(english="bean", target="muume"),
    VocabEntry(english="peyote", target="hikuri"),
    VocabEntry(english="papaya", target="papaya"),
    VocabEntry(english="fruit", target="kukuriyari"),
    VocabEntry(english="seed", target="hayari"),
    VocabEntry(english="plant", target="iweka"),
    VocabEntry(english="leaf", target="iwaka"),
    VocabEntry(english="root", target="hurawa"),
    # Nature & places
    VocabEntry(english="water", target="há"),
    VocabEntry(english="fire", target="tai"),
    VocabEntry(english="sun", target="táu"),
    VocabEntry(english="moon", target="mecéri"),
    VocabEntry(english="star", target="x+rawe"),
    VocabEntry(english="sky", target="taheima"),
    VocabEntry(english="cloud", target="hai"),
    VocabEntry(english="rain", target="wikie"),
    VocabEntry(english="stone", target="tete"),
    VocabEntry(english="earth", target="kiekari"),
    VocabEntry(english="land", target="kiekari"),
    VocabEntry(english="ground", target="kwie"),
    VocabEntry(english="mountain", target="kieri"),
    VocabEntry(english="road", target="huyé"),
    VocabEntry(english="path", target="huyé"),
    VocabEntry(english="river", target="há apá"),
    VocabEntry(english="desert", target="witari"),
    VocabEntry(english="forest", target="kiyete"),
    VocabEntry(english="field", target="iwama"),
    VocabEntry(english="world", target="kiekari"),
    # Built environment
    VocabEntry(english="house", target="kí"),
    VocabEntry(english="home", target="kie"),
    VocabEntry(english="community", target="kiekari"),
    VocabEntry(english="village", target="kiekari"),
    VocabEntry(english="town", target="kiekari"),
    VocabEntry(english="bridge", target="háne"),
    VocabEntry(english="corral", target="kuraru"),
    VocabEntry(english="pen", target="kuraru"),
    VocabEntry(english="temple", target="teyupani"),
    VocabEntry(english="church", target="teyupani"),
    VocabEntry(english="ceremonial_center", target="tukipa"),
    VocabEntry(english="ramada", target="ramaru"),
    VocabEntry(english="building", target="ramaru"),
    VocabEntry(english="school", target="kit+wame"),
    VocabEntry(english="kitchen", target="ikwaitsie"),
    VocabEntry(english="room", target="ramaru"),
    # Artifacts & clothing
    VocabEntry(english="clothing", target="kemarite"),
    VocabEntry(english="clothes", target="kemarite"),
    VocabEntry(english="shirt", target="kemari"),
    VocabEntry(english="skirt", target="'iwi"),
    VocabEntry(english="blouse", target="kutuni"),
    VocabEntry(english="hat", target="xupureru"),
    VocabEntry(english="bag", target="temawiet+"),
    VocabEntry(english="backpack", target="tacuats"),
    VocabEntry(english="knife", target="tsiuri"),
    VocabEntry(english="book", target="xapa"),
    VocabEntry(english="paper", target="xapa"),
    VocabEntry(english="basket", target="kiriwa"),
    VocabEntry(english="bowl", target="xukuri"),
    VocabEntry(english="gourd", target="xukuri"),
    VocabEntry(english="thread", target="wita"),
    VocabEntry(english="yarn", target="wita"),
    VocabEntry(english="bead", target="chakira"),
    VocabEntry(english="arrow", target="muwieri"),
    VocabEntry(english="drum", target="tepo"),
    VocabEntry(english="chair", target="uweni"),
    VocabEntry(english="table", target="mexa"),
    VocabEntry(english="cart", target="kareta"),
    VocabEntry(english="truck", target="kareta"),
    VocabEntry(english="car", target="kareta"),
    VocabEntry(english="tablet", target="nierika"),
    VocabEntry(english="painting", target="nierika"),
    VocabEntry(english="art", target="nierika"),
    VocabEntry(english="offering", target="xukuri"),
    VocabEntry(english="cloak", target="wipat+"),
    # Body
    VocabEntry(english="heart", target="iyari"),
    VocabEntry(english="head", target="muu"),
    VocabEntry(english="eye", target="h+xi"),
    VocabEntry(english="face", target="nierika"),
    VocabEntry(english="hand", target="mama"),
    VocabEntry(english="foot", target="kutsi"),
    VocabEntry(english="tail", target="kwaxi"),
    VocabEntry(english="horn", target="awa"),
]

TRANSITIVE_VERBS = [
    VocabEntry(english="eat", target="wa"),
    VocabEntry(english="drink", target="i'i"),
    VocabEntry(english="see", target="niere"),
    VocabEntry(english="look_at", target="xeiya"),
    VocabEntry(english="watch", target="xeiya"),
    VocabEntry(english="have", target="xeiya"),
    VocabEntry(english="carry", target="ikata"),
    VocabEntry(english="make", target="wewiya"),
    VocabEntry(english="build", target="wewiya"),
    VocabEntry(english="do", target="'iya"),
    VocabEntry(english="cook", target="kari"),
    VocabEntry(english="harvest", target="mati"),
    VocabEntry(english="wash", target="ekwá"),
    VocabEntry(english="embroider", target="wipa"),
    VocabEntry(english="herd", target="waiya"),
    VocabEntry(english="buy", target="nanai"),
    VocabEntry(english="sell", target="nanai"),
    VocabEntry(english="guard", target="xainé"),
    VocabEntry(english="find", target="ni'iwa"),
    VocabEntry(english="scare", target="weiya"),
    VocabEntry(english="hear", target="'eni"),
    VocabEntry(english="know", target="mate"),
    VocabEntry(english="take", target="kuwiya"),
    VocabEntry(english="give", target="k+ni"),
    VocabEntry(english="bring", target="utá"),
    VocabEntry(english="plant", target="'+ka"),
    VocabEntry(english="hunt", target="nayari"),
    VocabEntry(english="tell", target="tanyu"),
    VocabEntry(english="write", target="ut+a"),
    VocabEntry(english="read", target="'utiwa"),
    VocabEntry(english="hold", target="'+k+"),
    VocabEntry(english="use", target="parewi"),
    VocabEntry(english="wear", target="ranakat+"),
]

INTRANSITIVE_VERBS = [
    VocabEntry(english="rest", target="tsunawa"),
    VocabEntry(english="walk", target="mie"),
    VocabEntry(english="sit", target="kat+"),
    VocabEntry(english="stand", target="ti"),
    VocabEntry(english="sleep", target="ku'u"),
    VocabEntry(english="go", target="yaha"),
    VocabEntry(english="come", target="niuwa"),
    VocabEntry(english="arrive", target="heu"),
    VocabEntry(english="run", target="tita"),
    VocabEntry(english="live", target="hupú"),
    VocabEntry(english="work", target="iwa"),
    VocabEntry(english="enjoy", target="ts+a"),
    VocabEntry(english="dance", target="neixa"),
    VocabEntry(english="sing", target="nierika"),
    VocabEntry(english="play", target="temai"),
    VocabEntry(english="laugh", target="tsetsere"),
    VocabEntry(english="cry", target="'uka"),
    VocabEntry(english="speak", target="niu"),
    VocabEntry(english="talk", target="niu"),
    VocabEntry(english="pray", target="niuwari"),
    VocabEntry(english="grow", target="iweka"),
    VocabEntry(english="die", target="muk+"),
    VocabEntry(english="be_born", target="niutsi"),
    VocabEntry(english="exist", target="ane"),
    VocabEntry(english="fly", target="'+tsa"),
    VocabEntry(english="swim", target="uyu"),
    VocabEntry(english="travel", target="mie"),
    VocabEntry(english="return", target="pa+"),
    VocabEntry(english="fall", target="wauka"),
    VocabEntry(english="rise", target="'ane"),
]
